define([], function() {
  return {
    "userLang": "EN",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "altImgLogo": "Logo of",
    "pagPrev": "Previous",
    "pagNext": "Next",
    "setTitleEn": "Title in english",
    "setTitleFr": "Title in french",
    "setPageNum": "Number per page",
    "setLayoutOpt": "Layout option",
    "setSortOpt": "Sort option",
    "gridIcon": "Grid",
    "compactIcon": "Compact",
    "dateCreation": "Creation date",
    "alphabetical": "Alphabetical",
    "showmore": "Show more",
    "showless": "Show less",
    "members": "members",
    "seeAllLink": "Link for see all",
    "seeAll": "See all",
    "seeAllLabel": "See all of my communities",
    "ListIcon": "List",
    "createCommLink": "Link for create a community",
    "createComm": "Create a community",
    "seeAllToggle": "This webpart is for the see all page",
    "seeAllOn": "Yes",
    "seeAllOff": "No",
    "loadingState": "Loading"
  }
});
