define([], function() {
  return {
    "userLang": "FR",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "altImgLogo": "Logo de",
    "pagPrev": "Précédant",
    "pagNext": "Suivant",
    "setTitleEn": "Titre en anglais",
    "setTitleFr": "Titre en français",
    "setPageNum": "Nombre par page",
    "setLayoutOpt": "Option de mise en page",
    "setSortOpt": "Option de tri",
    "gridIcon": "Grille",
    "compactIcon": "Compacte",
    "dateCreation": "Date de création",
    "alphabetical": "Alphabétique",
    "showmore": "Montrer plus",
    "showless": "Montrer moins",
    "members": "membres",
    "seeAllLink": "Lien pour Afficher tout",
    "seeAll": "Afficher tout",
    "seeAllLabel": "Afficher toutes mes collectivités",
    "ListIcon": "Liste",
    "createCommLink": "Lien pour créer une collectivité",
    "createComm": "Créez une collectivité",
    "seeAllToggle": "Ce webpart est pour la page Afficher tout",
    "seeAllOn": "Oui",
    "seeAllOff": "Non",
    "loadingState": "Chargement en cours"
  }
});
